### PR TITLE
Bug fix nested array children

### LINKED ISSUE #3: Does not handle nested arrays
This only occurs when the JSX creates a nested array of elements e.g.

```tsx
<div>
  {arr.map(() => <li />)}
  <p />
</div>
```

Which compiles to, roughly:

```tsx
{
  type: 'div',
  props: {
    children: [
      [{type: 'li'}],
      {type: 'p'}
    ]
  }
}
```

For now you can avoid the errors by wrapping each child in `<></>` e.g.

```jsx
<div>
  <>
    {arr.map(() => <li />)}
  </>
  <>
    <p />
  </>
</div>
```

### PR DESCRIPTION
**Pull request by JakeSidSmith**
Fixes #3 

Allows nested arrays of children to be rendered e.g.

```jsx
<div>
  {[1].map((child) => <li key={child}>{child}</li>)}
  <p />
</div>
```

Returns a node structure like (pseudo code):

```
{
  div,
  children: [
    [
      { li }
    ],
    { div }
  ]
}
```

### CODE REVIEW

File: src/guards.ts [hunk 1]
```diff
@@ -84,3 +86,7 @@ export function isForwardRef(node: ReactAnyNode): node is ReactForwardRefNode {
 export function isPortal(node: ReactAnyNode): node is ReactDOMPortalNode {
   return node.$$typeof === portalSymbol;
 }
+
+export function isArray(node: ReactAnyChildren): node is ReactAnyChildrenArray {
```
Comment (AngryLawyer) [inline src/guards.ts]: I'd probably give this a slightly longer name, as it is a little confusing with Array.isArray
